### ISSUE TITLE
About the global default instance

### ISSUE THREAD

**Issue by joe-sky** [superwf/fxios#2]
Have you considered export a global default fxios instance? as axios:

```js
import fxios from 'fxios'

fxios.get(…)
fxios.post(…)
```

For keep library size, so haven't do as above one?

**Comment by superwf** [comment]
use it this way in the entry file.
`
import { Fxios } from 'fxios'

window.fxios = new Fxios()
`
and then use it as global.

**Comment by joe-sky** [comment]
Eh...Yes, it can be used that way :flushed: . But the following is what I want to express actually:

1. If `fxios` has the global default instance as `axios`, then maybe it will be easier to use.
2. If their APIs are more similar, the users can better migrate from `axios` to `fxios`.

Similarly, I also find their response parameter structures are different.

These are just my suggestions, thx~

**Comment by superwf** [comment]
yes, it should be compiled to be a global variable and could be used by cdn like unpkg.com.
I will make it later.
